# Hericles Bruno Quaresma Koelher

all: atividadePipes

atividadePipes: atividadePipes.o
	gcc -o atividadePipes atividadePipes.c

clean:
	rm atividadePipes.o atividadePipes PipePing.txt

run:
	./atividadePipes